'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createContext, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const ThemeContext = createContext({
  theme: '',
  setTheme: (theme: string) => {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setTheme] = useState(window.matchMedia('(prefers-color-scheme: dark)').matches? 'dark' : '');
      <ThemeContext.Provider value={{theme: theme, setTheme:setTheme}}>
        {children}
      </ThemeContext.Provider>
  return (
    <html lang="en" className={theme}>
      <ThemeContext.Provider value={{theme: theme, setTheme:setTheme}}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-sky-950 bg-sky-300 text-sky-900 dark:text-sky-50`}
      >
        {children}
      </body>
      </ThemeContext.Provider>
    </html>
  );
}
